
/*
 * 
 */

package com.threeti.umax.sample.composite.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-09-14T17:36:17.227+08:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "FinancialRiskEvaluationService", 
                  wsdlLocation = "http://localhost:9090/services/FinancialRiskEvaluationService?wsdl",
                  targetNamespace = "http://service.composite.sample.umax.threeti.com/") 
public class FinancialRiskEvaluationService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.composite.sample.umax.threeti.com/", "FinancialRiskEvaluationService");
    public final static QName FinancialRiskEvaluationManagerImplPort = new QName("http://service.composite.sample.umax.threeti.com/", "FinancialRiskEvaluationManagerImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/services/FinancialRiskEvaluationService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FinancialRiskEvaluationService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/services/FinancialRiskEvaluationService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FinancialRiskEvaluationService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FinancialRiskEvaluationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FinancialRiskEvaluationService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns FinancialRiskEvaluationService
     */
    @WebEndpoint(name = "FinancialRiskEvaluationManagerImplPort")
    public FinancialRiskEvaluationService getFinancialRiskEvaluationManagerImplPort() {
        return super.getPort(FinancialRiskEvaluationManagerImplPort, FinancialRiskEvaluationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FinancialRiskEvaluationService
     */
    @WebEndpoint(name = "FinancialRiskEvaluationManagerImplPort")
    public FinancialRiskEvaluationService getFinancialRiskEvaluationManagerImplPort(WebServiceFeature... features) {
        return super.getPort(FinancialRiskEvaluationManagerImplPort, FinancialRiskEvaluationService.class, features);
    }

}
