package com.threeti.umax.sample.composite.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-09-14T17:36:17.181+08:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://service.composite.sample.umax.threeti.com/", name = "FinancialRiskEvaluationService")
@XmlSeeAlso({ObjectFactory.class, com.threeti.umax.sample.salesmockapp.service.ObjectFactory.class})
public interface FinancialRiskEvaluationService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "existCreditRisk", targetNamespace = "http://service.composite.sample.umax.threeti.com/", className = "com.threeti.umax.sample.composite.service.ExistCreditRisk")
    @WebMethod
    @ResponseWrapper(localName = "existCreditRiskResponse", targetNamespace = "http://service.composite.sample.umax.threeti.com/", className = "com.threeti.umax.sample.composite.service.ExistCreditRiskResponse")
    public java.lang.Boolean existCreditRisk(
        @WebParam(name = "arg0", targetNamespace = "")
        com.threeti.umax.sample.salesmockapp.service.Contract arg0
    );
}
