package com.threeti.umax.sample.financialmockapp.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-09-23T17:36:17.238+08:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://service.financialmockapp.sample.umax.threeti.com/", name = "CreditService")
@XmlSeeAlso({ObjectFactory.class})
public interface CreditService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveCredit", targetNamespace = "http://service.financialmockapp.sample.umax.threeti.com/", className = "com.threeti.umax.sample.financialmockapp.service.SaveCredit")
    @WebMethod
    @ResponseWrapper(localName = "saveCreditResponse", targetNamespace = "http://service.financialmockapp.sample.umax.threeti.com/", className = "com.threeti.umax.sample.financialmockapp.service.SaveCreditResponse")
    public com.threeti.umax.sample.financialmockapp.service.Credit saveCredit(
        @WebParam(name = "arg0", targetNamespace = "")
        com.threeti.umax.sample.financialmockapp.service.Credit arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCredits", targetNamespace = "http://service.financialmockapp.sample.umax.threeti.com/", className = "com.threeti.umax.sample.financialmockapp.service.GetCredits")
    @WebMethod
    @ResponseWrapper(localName = "getCreditsResponse", targetNamespace = "http://service.financialmockapp.sample.umax.threeti.com/", className = "com.threeti.umax.sample.financialmockapp.service.GetCreditsResponse")
    public java.util.List<com.threeti.umax.sample.financialmockapp.service.Credit> getCredits();

    @WebResult(name = "credit", targetNamespace = "")
    @RequestWrapper(localName = "getCustomerCredit", targetNamespace = "http://service.financialmockapp.sample.umax.threeti.com/", className = "com.threeti.umax.sample.financialmockapp.service.GetCustomerCredit")
    @WebMethod
    @ResponseWrapper(localName = "getCustomerCreditResponse", targetNamespace = "http://service.financialmockapp.sample.umax.threeti.com/", className = "com.threeti.umax.sample.financialmockapp.service.GetCustomerCreditResponse")
    public com.threeti.umax.sample.financialmockapp.service.Credit getCustomerCredit(
        @WebParam(name = "customerId", targetNamespace = "")
        java.lang.String customerId
    );

    @WebResult(name = "credit", targetNamespace = "")
    @RequestWrapper(localName = "getCredit", targetNamespace = "http://service.financialmockapp.sample.umax.threeti.com/", className = "com.threeti.umax.sample.financialmockapp.service.GetCredit")
    @WebMethod
    @ResponseWrapper(localName = "getCreditResponse", targetNamespace = "http://service.financialmockapp.sample.umax.threeti.com/", className = "com.threeti.umax.sample.financialmockapp.service.GetCreditResponse")
    public com.threeti.umax.sample.financialmockapp.service.Credit getCredit(
        @WebParam(name = "creditId", targetNamespace = "")
        java.lang.String creditId
    );
}
