package com.threeti.umax.sample.financialmockapp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-20T14:45:13.344+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "CreditService", 
                  wsdlLocation = "http://localhost:9090/services/CreditService?wsdl",
                  targetNamespace = "http://service.financialmockapp.sample.umax.threeti.com/") 
public class CreditService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.financialmockapp.sample.umax.threeti.com/", "CreditService");
    public final static QName CreditManagerImplPort = new QName("http://service.financialmockapp.sample.umax.threeti.com/", "CreditManagerImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/services/CreditService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreditService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/services/CreditService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreditService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreditService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CreditService
     */
    @WebEndpoint(name = "CreditManagerImplPort")
    public CreditService getCreditManagerImplPort() {
        return super.getPort(CreditManagerImplPort, CreditService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditService
     */
    @WebEndpoint(name = "CreditManagerImplPort")
    public CreditService getCreditManagerImplPort(WebServiceFeature... features) {
        return super.getPort(CreditManagerImplPort, CreditService.class, features);
    }

}
