
package com.threeti.umax.sample.salesmockapp.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-09-13T16:58:31.199+08:00
 * Generated source version: 2.4.0
 * 
 */
public final class ContractService_ContractManagerImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.salesmockapp.sample.umax.threeti.com/", "ContractService");

    private ContractService_ContractManagerImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ContractService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ContractService_Service ss = new ContractService_Service(wsdlURL, SERVICE_NAME);
        ContractService port = ss.getContractManagerImplPort();  
        
        {
        System.out.println("Invoking saveContract...");
        com.threeti.umax.sample.salesmockapp.service.Contract _saveContract_arg0 = null;
        com.threeti.umax.sample.salesmockapp.service.Contract _saveContract__return = port.saveContract(_saveContract_arg0);
        System.out.println("saveContract.result=" + _saveContract__return);


        }
        {
        System.out.println("Invoking getContracts...");
        java.util.List<com.threeti.umax.sample.salesmockapp.service.Contract> _getContracts__return = port.getContracts();
        System.out.println("getContracts.result=" + _getContracts__return);


        }
        {
        System.out.println("Invoking getContract...");
        java.lang.String _getContract_arg0 = "";
        com.threeti.umax.sample.salesmockapp.service.Contract _getContract__return = port.getContract(_getContract_arg0);
        System.out.println("getContract.result=" + _getContract__return);


        }

        System.exit(0);
    }

}
